# Optson Config (https://github.com/dirkphilip/Optson)

# Smoothing length of the gradients, in radial and lateral directions.
gradient_smoothing_length = [ 0.4, 0.8, 0.8,]

# The starting model. This must be a .h5 file as provided by the Salvus Mesher.
initial_model = ""

# Maximum number of iterations to perform.
max_iterations = 1000

# Smoothing timestep, must be either "auto" for automatic timesteps or a float.
smoothing_timestep = "auto"

# Calls Optson gradient test instead of the inversion.
do_gradient_test = false

# Use isotropic VP. This requires the starting model to have VPV=VPH and ETA=`
isotropic_vp = true